import ACTIVITY_AT_ONSET from '@/assets/data/answers/ACTIVITY_AT_ONSET.json';
import ALCOHOL_USE from '@/assets/data/answers/ALCOHOL_USE.json';
import ALLERGIES from '@/assets/data/answers/ALLERGIES.json';
import ASSOCIATED_SYMPTOMS from '@/assets/data/answers/ASSOCIATED_SYMPTOMS.json';
import BROUGHT_MEDICAL_REPORT from '@/assets/data/answers/BROUGHT_MEDICAL_REPORT.json';
import BROUGHT_PRESCRIPTION from '@/assets/data/answers/BROUGHT_PRESCRIPTION.json';
import COVID_VACCINATION from '@/assets/data/answers/COVID_VACCINATION.json';
import CURRENT_MEDICATIONS from '@/assets/data/answers/CURRENT_MEDICATIONS.json';
import FIRST_EPISODE_TIME from '@/assets/data/answers/FIRST_EPISODE_TIME.json';
import FLU_VACCINATION from '@/assets/data/answers/FLU_VACCINATION.json';
import PAIN_DESCRIPTION from '@/assets/data/answers/PAIN_DESCRIPTION.json';
import PAIN_EVOLUTION from '@/assets/data/answers/PAIN_EVOLUTION.json';
import PAIN_INTENSITY_SCALE from '@/assets/data/answers/PAIN_INTENSITY_SCALE.json';
import PAIN_LOCATION_SPREAD from '@/assets/data/answers/PAIN_LOCATION_SPREAD.json';
import PAIN_RELIEVING_FACTORS from '@/assets/data/answers/PAIN_RELIEVING_FACTORS.json';
import PAIN_WORSENING_FACTORS from '@/assets/data/answers/PAIN_WORSENING_FACTORS.json';
import PREVIOUS_SURGERY from '@/assets/data/answers/PREVIOUS_SURGERY.json';
import PREVIOUS_TREATMENT from '@/assets/data/answers/PREVIOUS_TREATMENT.json';
import REASON_HOSPITAL_VISIT from '@/assets/data/answers/REASON_HOSPITAL_VISIT.json';
import RECENT_WORSENING from '@/assets/data/answers/RECENT_WORSENING.json';
import SINGLE_OR_MULTIPLE_EPISODES from '@/assets/data/answers/SINGLE_OR_MULTIPLE_EPISODES.json';
import SMOKING_STATUS from '@/assets/data/answers/SMOKING_STATUS.json';
import SYMPTOM_ONSET_TIME from '@/assets/data/answers/SYMPTOM_ONSET_TIME.json';
import VACCINE_CARD_BROUGHT from '@/assets/data/answers/VACCINE_CARD_BROUGHT.json';
import { Answer } from '@/types/stacks';

export const ANSWERS: Record<string, Answer[]> = {
    "ACTIVITY_AT_ONSET": ACTIVITY_AT_ONSET,
    "ALCOHOL_USE": ALCOHOL_USE,
    "ALLERGIES": ALLERGIES,
    "ASSOCIATED_SYMPTOMS": ASSOCIATED_SYMPTOMS,
    "BROUGHT_MEDICAL_REPORT": BROUGHT_MEDICAL_REPORT,
    "BROUGHT_PRESCRIPTION": BROUGHT_PRESCRIPTION,
    "COVID_VACCINATION": COVID_VACCINATION,
    "CURRENT_MEDICATIONS": CURRENT_MEDICATIONS,
    "FIRST_EPISODE_TIME": FIRST_EPISODE_TIME,
    "FLU_VACCINATION": FLU_VACCINATION,
    "PAIN_DESCRIPTION": PAIN_DESCRIPTION,
    "PAIN_EVOLUTION": PAIN_EVOLUTION,
    "PAIN_INTENSITY_SCALE": PAIN_INTENSITY_SCALE,
    "PAIN_LOCATION_SPREAD": PAIN_LOCATION_SPREAD,
    "PAIN_RELIEVING_FACTORS": PAIN_RELIEVING_FACTORS,
    "PAIN_WORSENING_FACTORS": PAIN_WORSENING_FACTORS,
    "PREVIOUS_SURGERY": PREVIOUS_SURGERY,
    "PREVIOUS_TREATMENT": PREVIOUS_TREATMENT,
    "REASON_HOSPITAL_VISIT": REASON_HOSPITAL_VISIT,
    "RECENT_WORSENING": RECENT_WORSENING,
    "SINGLE_OR_MULTIPLE_EPISODES": SINGLE_OR_MULTIPLE_EPISODES,
    "SMOKING_STATUS": SMOKING_STATUS,
    "SYMPTOM_ONSET_TIME": SYMPTOM_ONSET_TIME,
    "VACCINE_CARD_BROUGHT": VACCINE_CARD_BROUGHT,
};
